#!/bin/bash

# shellcheck disable=SC2164
cd "$(dirname "$(readlink -f "$0")")"  # "

CP=

nohup java -classpath "./out/production/GameTemplate:$CP" ru.vsu.cs.course1.game.Program "$@" >/dev/null 2>&1 &
